// The opening block of the generated file, orienting the agent before any rules.

export const id = 'header';
export const number = null;
export const title = 'Header';
export const when = () => true;

export function text(signals) {
  return `# {{PROJECT_NAME}}

This file is generated by agentic from the state of this repository. It
tells an AI agent working here what the project is, how it is built, and
what rules apply before any change is made.

If the repository changes in a way this file no longer reflects, regenerate
it rather than editing around the gap.`;
}
