// Codex reads the same .agents/skills layout, plus an interface adapter that
// supplies the name, blurb, and opening prompt its picker shows.
//
// The adapter carries no logic. Everything that changes agent behavior lives in
// the compiled SKILL.md, so a tool that ignores this file loses nothing but the
// picker entry.

export const id = 'codex';
export const label = 'OpenAI Codex';
export const detect = '.agents';

const quote = (value) => `"${String(value).replace(/"/g, '\\"')}"`;

function adapter({ name, skill }) {
  const description = skill.frontmatter.description ?? '';
  return `# Interface metadata for Codex. Generated by agentic. Do not edit by hand.
interface:
  name: ${name}
  description: ${quote(description)}
  prompt: ${quote(`Run the ${name} skill.`)}
`;
}

export function plan({ root, name, compiled, skill }) {
  return [
    { path: `${root}/.agents/skills/${name}/SKILL.md`, contents: compiled },
    { path: `${root}/.agents/skills/${name}/agents/openai.yaml`, contents: adapter({ name, skill }) },
  ];
}
