// Codex reads the same .agents/skills layout, plus an interface adapter that
// supplies the name, blurb, and opening prompt its picker shows.
//
// The adapter carries no logic. Everything that changes agent behavior lives in
// the compiled SKILL.md, so a tool that ignores this file loses nothing but the
// picker entry.

import { withAssets } from './assets.mjs';

export const id = 'codex';
export const label = 'OpenAI Codex (.agents/skills plus a picker adapter)';

// Deliberately not auto detected. Codex reads the same .agents directory the
// generic target writes, so detecting both would plan the same SKILL.md twice.
// The open layout is the neutral default; this adapter is opt in with
// `-t codex`, because its openai.yaml is useful only to Codex itself.
export const detect = null;

const quote = (value) => `"${String(value).replace(/"/g, '\\"')}"`;

function adapter({ name, skill }) {
  const description = skill.frontmatter.description ?? '';
  return `# Interface metadata for Codex. Generated by agentic. Do not edit by hand.
interface:
  name: ${name}
  description: ${quote(description)}
  prompt: ${quote(`Run the ${name} skill.`)}
`;
}

export const carriesAssets = true;

export function plan({ root, name, compiled, skill, assets }) {
  const dir = `${root}/.agents/skills/${name}`;
  return withAssets(
    [
      { path: `${dir}/SKILL.md`, contents: compiled },
      { path: `${dir}/agents/openai.yaml`, contents: adapter({ name, skill }) },
    ],
    dir,
    assets,
  );
}
